#!/usr/bin/env zsh
# Install macOS apps
echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> /Users/`echo $USER`/.zprofile;
eval "$(/opt/homebrew/bin/brew shellenv)";
brew tap homebrew/cask-fonts && brew install --cask font-fira-code &&
for x in iterm2 visual-studio-code rectangle 1password google-chrome adobe-acrobat-reader docker; do brew install --cask $x; done &&
echo "------------------------\n\nInstalled apps:\n---------------\n" &&
brew list --cask -1 &&
brew tap homebrew/cask-versions && brew install --cask firefox-developer-edition --lang=en-US &&
echo "------------------------\n\nInstall DDEV\n---------------\n" &&
brew install ddev/ddev/ddev