#!/usr/bin/env zsh
# Install macOS apps
brew tap homebrew/cask-fonts && brew install --cask font-fira-code &&
for x in iterm2 visual-studio-code rectangle 1password google-chrome adobe-acrobat-reader docker ddev/ddev/ddev; do brew install --cask $x; done &&
echo "------------------------\n\nInstalled apps:\n---------------\n" &&
brew list --cask -1 &&
brew tap homebrew/cask-versions && brew install --cask firefox-developer-edition --lang=en-US